name: Environments variables
on: push
jobs:
  run:
    runs-on: unbutu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}