name: Explain C Code

on:
  workflow_dispatch:

jobs:
  explain-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get file from GitHub API
        run: |
          curl -H "Accept: application/vnd.github.v3.raw" \
               https://api.github.com/repos/miork0425/my-repo/contents/path/to/go/excellent/main.go \
               -o main.go

      - name: Send file to OpenAI API for explanation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          CONTENT=$(cat file.c | jq -Rs .)
          curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {"role": "system", "content": "あなたはC言語の専門家です。"},
                {"role": "user", "content": "次のコードを説明してください：" },
                {"role": "user", "content": '"$CONTENT"' }
              ]
            }'

      - name: Show result
        run: echo "説明結果は上のステップで表示されます"