name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello world
        required: true
        description: A cheerful word
jobs:
  run:
    run-on: windows-latest
    steps:
      - run: echo "${{ inputs.greeting }}"